### ISSUE TITLE
Need Instructions on how to properly install Gapps on v6.0.1

### ISSUE THREAD

**Issue by heri16** [UDOOboard/android_udoo_platform_manifest#1]

**Comment by fmntf** [comment]
Hi. Thank you for your interest. We are currently fixing low level things. Google Apps is a priority, but we have not addressed it yet.
In any case, in the final release, Google Apps will be supported.

**Comment by heri16** [comment]
Is gapps now supported? Are there instructions?

**Comment by fmntf** [comment]
Yes. See the [documentation](http://www.udoo.org/docs/Cookbook_Android/How_To_Install_Gapps_On_UDOO_Running_Android.html).
