### ISSUE TITLE
Build failed!

### ISSUE THREAD

**Issue by britus** [UDOOboard/android_udoo_platform_manifest#3]
No private recovery resources for TARGET_DEVICE udoo_6dq
build/core/Makefile:34: warning: overriding commands for target `out/target/product/udoo_6dq/root/init.rc'
build/core/base_rules.mk:316: warning: ignoring old commands for target `out/target/product/udoo_6dq/root/init.rc'
Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'out/target/product/udoo_6dq/obj/SHARED_LIBRARIES/libfuse_intermediates/export_includes', needed by 'out/target/product/udoo_6dq/obj/EXECUTABLES/fsck.ntfs_intermediates/import_includes', missing and no known rule to make it
build/core/ninja.mk:148: die Regel für Ziel „ninja_wrapper“ scheiterte
make: *** [ninja_wrapper] Fehler 1

**Comment by secuflag** [comment]
Which branch? _android-6.0.1_ or _android-7.1_?

**Comment by britus** [comment]
Hi,
it's branch android-7.1.

...: ~/embedded/udoo-quad/android-7# source c.sh 
including device/udoo/imx6/vendorsetup.sh
including sdk/bash_completion/adb.bash
```
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
TARGET_PRODUCT=udoo_6dq
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a9
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.13.0-21-lowlatency-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=7.1.1-dev
OUT_DIR=out
============================================
```

**Comment by secuflag** [comment]
Branch _android-7.1_ it's still a WIP here, checkout the _android-6.0.1_ or take a look at https://github.com/udoo-android-nougat/android_manifest (more info at https://www.udoo.org/forum/threads/android-7-x-nougat-su-dual-quad-e-neo.10825/#post-33946)

**Comment by secuflag** [comment]
Fixed in https://github.com/UDOOboard/android_udoo_platform_manifest/commit/ea898a58fd07ecbcb7e8048e756e3cc4109012da
